### ISSUE TITLE
Break down the Maintain category

### ISSUE THREAD

**Issue by mreferre** [cremich/promptz#58]
**Is your feature request related to a problem? Please describe.**
The category `Maintain` seems to be a very broad catch all. As it stands today it would need to capture all operational aspects associated to [Q Actions](https://docs.aws.amazon.com/amazonq/latest/qdeveloper-ug/chat-actions.html), all "FinOps" aspects associated to [billing](https://docs.aws.amazon.com/amazonq/latest/qdeveloper-ug/chat-costs.html), all support aspects associate to [support](https://docs.aws.amazon.com/amazonq/latest/qdeveloper-ug/support-chat.html), and last but not least all operational aspects associated to [3P extensions](https://docs.aws.amazon.com/amazonq/latest/qdeveloper-ug/plugins.html). 
It seems like a too broad catch all category.  

**Describe the solution you'd like**
I don't have a specific suggestion and I'd like to use this issue to brainstorm re what's the right break down of categories.

**Describe alternatives you've considered**
Adding all prompts to the `Maintain` category. This can be done today but it's probably not ideal.

**Additional context**
None

**Comment by cremich** [comment]
Thank you @mreferre for your feedback. Let us get some inspiration and ask the community here: 

**What is the ideal breakdown of the SDLC phase that guides you best in adding your prompts to PROMPTZ?"**

**Comment by cremich** [comment]
I asked my friend **Q Developer** about it and here is what I got 😉 In general I like the suggestions and don't want to be too pedantic on the definition of the SDLC Phases. But maybe "SDLC Activity" is a better term when making these changes. Let me think about it.
---
Based on the feedback, I agree that the MAINTAIN phase could be broken down into more specific categories to better reflect the different aspects of post-deployment software management. Here's a suggested breakdown of the MAINTAIN phase into more granular categories:
```
export enum SdlcPhase {
  PLAN = "Plan",
  REQ = "Requirements",
  DESIGN = "Design",
  IMPLEMENT = "Implement",
  TEST = "Test",
  DEPLOY = "Deploy",
  
  // New breakdown of MAINTAIN into specific categories
  OPERATE = "Operate",          // Day-to-day operations, monitoring, alerting
  OPTIMIZE = "Optimize",        // Performance tuning, FinOps, cost optimization
  SUPPORT = "Support",         // User support, troubleshooting, bug fixes
  ENHANCE = "Enhance",         // Feature enhancements, updates, patches
  INTEGRATE = "Integrate",     // 3P extensions, integrations management
  
  UNKNOWN = "Unknown",
}
```

This breakdown offers several advantages:

- OPERATE : Focuses specifically on operational aspects like system monitoring, health checks, and day-to-day maintenance activities
- OPTIMIZE : Dedicated category for performance and cost optimization activities, including FinOps aspects
- SUPPORT : Covers all support-related activities, including user assistance, incident management, and bug resolution
- ENHANCE : Addresses continuous improvement through feature updates and patches
- INTEGRATE : Specifically handles third-party extension management and integration concerns

This granular approach would:

- Make it easier to categorize specific activities
- Provide better metrics and insights into different types of maintenance activities
- Allow for more focused resource allocation
- Enable better tracking of different post-deployment activities

Alternative approaches could include:

- Creating sub-categories within MAINTAIN
- Grouping some of these categories together if they're too granular
- Adding specific flags or attributes to indicate the type of maintenance activity
- Would you like to explore any of these alternatives in more detail or discuss the proposed breakdown further?

**Comment by mreferre** [comment]
It's definitely going into the direction I was thinking. I like it.

**Comment by cremich** [comment]
This is the current plan:

1. Rename SDLC Phase to SDLC Activity in the UI 
2. Add the proposed activities to the current list and remove "maintain" (for now no prompts are created in this phase)
3. Make SDLC Activity optional so users can publish a prompt without being forced to decide here. 

This gives PROMPTZ flexibility to add further needed activities in the future.
